TransparenciaRO.Web/Controllers/MenuController.cs
using CaptchaMvc.HtmlHelpers;
using reCAPTCHA.MVC;
using System;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using TransparenciaRO.Business;
using TransparenciaRO.Infra.DAL;
using TransparenciaRO.Infra.Model.View;
using TransparenciaRO.Infra.Utils;
using static System.Configuration.ConfigurationManager;

namespace TransparenciaRO.Web.Controllers
{
    public class MenuController : ControllerBase
    {
        private readonly DbTransparencia _dbTransparencia = new DbTransparencia();
        private readonly ContatoInstitucionalDAL _contatoInstitucionalDal;

        public MenuController()
        {
            _contatoInstitucionalDal = new ContatoInstitucionalDAL(_dbTransparencia);
        }

        public ActionResult Institucional()
        {
            var orgaos = new TbPllOrgaoSiafemBusiness().getOrgaos();
            return View(orgaos);
        }

        public ActionResult OPortal()
        {
            return View();
        }

        public ActionResult Legislacao()
        {
            return View();
        }

        public ActionResult InformacoesGerais()
        {
            return View();
        }

        public ActionResult PerguntasFrequentes()
        {
            return View();
        }

        public PartialViewResult FaleConosco()
        {
            return PartialView();
        }

        public ActionResult Acessibilidade()
        {
            return View();
        }

        [CaptchaValidator, HttpPost, ValidateAntiForgeryToken]
        public ActionResult FaleConosco(FaleConoscoViewModel faleConosco, bool captchaValid)
        {
            if (this.IsCaptchaValid("Captcha is not valid"))
            {

                var de = new MailAddress(AppSettings["mailContatoTo"], "Controladoria Geral do Estado / CGE");
                var para = new MailAddress(faleConosco.Email, faleConosco.Nome);
                var resposta = new MailMessage(de, para)
                {
                    Subject = "Contato",
                    Body = @"Prezado cidadão, agradecemos o seu contato, e caso for necessário, entraremos em contato em breve."
                };

                var msn = $"Nome: {faleConosco.Nome} \nEmail: {faleConosco.Email} \nFone: {faleConosco.Telefone} \nAssunto: {faleConosco.Assunto} \nMensagem: {faleConosco.Mensagem}";

                MailUtils.SendMail(msn);

                var smtp = new SmtpClient();
                smtp.Send(resposta);


                MensagemSucesso = "E-mail enviado com sucesso";
                return RedirectToAction("Index", "Home");

            }
            MensagemErro = "reCAPTCHA inválido";
            return RedirectToAction("Index", "Home");
        }

        public ActionResult ContatoInstitucional()
        {
            return View(_contatoInstitucionalDal.BuscarInstituicoes());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _dbTransparencia.Dispose();

            base.Dispose(disposing);
        }
    }
}

TransparenciaRO.Web/Views/Menu/Acessibilidade.cshtml
@{
    ViewBag.Title = "Acessibilidade";
}

<div class="container">
    <p>O portal de transparência de Rondônia disponibiliza atalhos de acessibilidade para o acesso aos serviços e informações aqui disponibilizadas.</p>
    <p>Os padrões de atalhos são:</p>
    <ul>
        <li>Utilizando <kbd>Alt + A</kbd> ou <kbd>Alt + Shift + A</kbd> em qualquer página, o usuário é direcionado para esta página contendo instruções de acessibilidade.</li>
        <li>Utilizando <kbd>Alt + 0</kbd> ou <kbd>Alt + Shift + 0</kbd> em qualquer página, o usuário é direcionado para a página inicial do portal.</li>
        <li>Utilizando <kbd>Alt + 1</kbd> ou <kbd>Alt + Shift + 1</kbd> em qualquer página, o usuário é direcionado para o topo da página atual.</li>
        <li>Utilizando <kbd>Alt + 2</kbd> ou <kbd>Alt + Shift + 2</kbd> em qualquer página, o usuário é direcionado para a seção Fale Conosco.</li>
        <li>Utilizando <kbd>Alt + 3</kbd> ou <kbd>Alt + Shift + 3</kbd> em qualquer página, o usuário ativa ou desativa o alto contraste.</li>
    </ul>
    <b>Leis e decretos sobre acessibilidade:</b>
    <ul>
        <li>Decreto nº 5.296 de 02 de dezembro de 2004 (<a href="http://www.planalto.gov.br/ccivil_03/_Ato2004-2006/2004/Decreto/D5296.htm">http://www.planalto.gov.br/ccivil_03/_Ato2004-2006/2004/Decreto/D5296.htm</a>).</li>
        <li>Decreto nº 6.949, de 25 de agosto de 2009 - Promulga a Convenção Internacional sobre os Direitos das Pessoas com Deficiência e seu Protocolo Facultativo, assinados em Nova York, em 30 de março de 2007 (<a href="http://www.planalto.gov.br/ccivil_03/_ato2007-2010/2009/decreto/d6949.htm">http://www.planalto.gov.br/ccivil_03/_ato2007-2010/2009/decreto/d6949.htm</a>).</li>
        <li>Decreto nº 7.724, de 16 de Maio de 2012 - Regulamenta a Lei No 12.527, que dispõe sobre o acesso a informações (<a href="http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2012/Decreto/D7724.htm">http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2012/Decreto/D7724.htm</a>).</li>
        <li>Modelo de Acessibilidade de Governo Eletrônico (<a href="http://www.governoeletronico.gov.br/acoes-e-projetos/e-MAG">http://www.governoeletronico.gov.br/acoes-e-projetos/e-MAG</a>).</li>
        <li>Portaria nº 03, de 07 de Maio de 2007 - formato .pdf (35,5Kb) - Institucionaliza o Modelo de Acessibilidade em Governo Eletrônico – e-MAG (<a href="http://www.governoeletronico.gov.br/biblioteca/arquivos/portaria-no-03-de-07-05-2007">http://www.governoeletronico.gov.br/biblioteca/arquivos/portaria-no-03-de-07-05-2007</a>)</li>
    </ul>
</div>

TransparenciaRO.Web/Views/Menu/ContatoInstitucional.cshtml
@using TransparenciaRO.Web.HTMLHelper
@model IEnumerable<TransparenciaRO.Infra.Model.DB.dbTransparencia.ContatoInstitucional>
@section Head{
    @Html.RenderizarReferenciasPorPlugin(new[] { EReferenciaHead.Mustache, EReferenciaHead.DataTable })
}
@{
    ViewBag.Title = "Contatos Instituicionais";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="col-md-12">
        <h3 class="text-center">
            Os arquivos abaixo referem-se à competência, legislação aplicável, principais cargos e seus ocupantes, endereço e telefones das unidades, bem horários de funcionamento das instituições do Estado de Rondônia
        </h3>
    </div>
    <table id="tabelaContatoInstitucional" class="table table-hover" width="100%">
        <thead>
            <tr>
                <th>Sigla</th>
                <th>Descrição</th>
                <th>Detalhes</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var contatoInstitucional in Model)
            {
                <tr>
                    <td>@contatoInstitucional.Sigla</td>
                    <td>@contatoInstitucional.Descricao</td>
                    <td>
                        <a href="@contatoInstitucional.EstruturaOrganizacional">
                            <i class="fa fa-link"></i> Clique aqui!
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section AposFooter
{
    <script>
        $("#tabelaContatoInstitucional").dataTablePadrao();
    </script>
}

TransparenciaRO.Web/Views/Menu/FaleConosco.cshtml
@model TransparenciaRO.Infra.Model.View.FaleConoscoViewModel
@using CaptchaMvc.HtmlHelpers

<div class="topMargin">
    @if (TempData["Erro"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>
                <span class="fa fa-thumbs-down"></span> Erro
            </strong>
            @TempData["Erro"].ToString()
        </div>
    }

    @if (TempData["Sucesso"] != null)
    {
        <div class="alert alert-success alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>
                <span class="fa fa-thumbs-up"></span>Sucesso
            </strong>
            @TempData["Sucesso"].ToString()
        </div>
    }
</div>

<h3>Fale Conosco</h3>
<p>
    Em caso de dúvidas, sugestões ou reclamações, entre em contato conosco através do formulário abaixo,
    faça sua solicitação de informação através do <a href="http://esic.cge.ro.gov.br/" target="_blank"><i class="fa fa-external-link"></i>eSIC</a>,
    ou presencialmente no <b>Palácio Rio Madeira - Edifício Rio Jamari</b>.
</p>
<p>Horário de atendimento ao público: 7:30h às 13:30h segunda-feira à sexta-feira.</p>
<p>
    Telefone: <a href="tel:6932165140">(69) 3212-9412</a><br />
    Telefone: <a href="tel:6932129407">(69) 3212-9407</a><br />
    Telefone: <a href="tel:69984829718">(69) 9 8482-9718</a><br />
    Telefone: <a href="tel:69984829781">(69) 9 8482-9781</a>
</p>
<p>
    <small>Campos obrigatórios <b class="text-danger" style="font-size: large">*</b></small>
</p>
@using (Html.BeginForm("FaleConosco", "Menu", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label class="control-label" for="@Html.IdFor(x => x.Nome)">
            Nome <b class="text-danger" style="font-size: large">*</b>
        </label>

        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", required = "required" } })
        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label class="control-label" for="@Html.IdFor(x => x.Telefone)">
            Telefone
        </label>

        <input class="form-control" name="@Html.NameFor(x=>x.Telefone)" id="@Html.IdFor(x=>x.Telefone)" />
        @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label class="control-label" for="@Html.IdFor(x => x.Email)">
            E-mail <b class="text-danger" style="font-size: large">*</b>
        </label>

        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", required = "required" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label class="control-label" for="@Html.IdFor(x => x.Assunto)">
            Assunto <b class="text-danger" style="font-size: large">*</b>
        </label>

        @Html.EditorFor(model => model.Assunto, new { htmlAttributes = new { @class = "form-control", required = "required" } })
        @Html.ValidationMessageFor(model => model.Assunto, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label class="control-label" for="@Html.IdFor(x => x.Mensagem)">
            Mensagem <b class="text-danger" style="font-size: large">*</b>
        </label>

        <textarea class="form-control" name="@Html.NameFor(x=>x.Mensagem)" id="@Html.IdFor(x=>x.Mensagem)" required="required" rows="5"></textarea>
        @Html.ValidationMessageFor(model => model.Mensagem, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <div class="form-group">
            @Html.Captcha("Atualizar", "Digite o código de segurança", 5, "Informe o código de segurança")
        </div>
    </div>


    <div class="form-group">
        <button type="submit" class="btn btn-default">
            <i class="fa fa-send"></i> Enviar
        </button>
    </div>
}

TransparenciaRO.Web/Views/Menu/InformacoesGerais.cshtml
@{
    ViewBag.Title = "Informações Gerais";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Informações Gerais</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

        </div>
    </div>
</div>

TransparenciaRO.Web/Views/Menu/Institucional.cshtml
@using TransparenciaRO.Web.HTMLHelper
@model IEnumerable<TransparenciaRO.Infra.Model.DB.dbTransparencia.OrgaoSiafem>
@section Head{
    @Html.RenderizarReferenciasPorPlugin(new[] { EReferenciaHead.DataTable })
}
@{
    ViewBag.Title = "Institucional - Órgãos e Unidades Gestoras";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover" id="tabelaInstitucional" style="width: 100%">
                <thead>
                    <tr>
                        <th>
                            Código
                        </th>
                        <th>
                            Nome
                        </th>
                        <th>
                            CNPJ
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>

                                @Html.DisplayFor(modelItem => item.ORGAO)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NOMEORGAO)
                            </td>
                            <td>
                                @Convert.ToUInt64(item.CGC).ToString(@"00\.000\.000\/0000\-00")
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section AposFooter{
    <script>
        $(document).ready(function () {
            $("#tabelaInstitucional").dataTablePadrao({});
        });
    </script>
}

TransparenciaRO.Web/Views/Menu/Legislacao.cshtml
@{
    ViewBag.Title = "Legislação - Lei de acesso à informação";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-body" style="text-align: justify">
                <p>
                    Com o amadurecimento da democracia, após quase uma década de tramitação no Congresso Nacional, entrou em vigor, a Lei de Acesso à Informação - LAI, que garante ampla divulgação dos interessados a dados e documentos das esferas da administração pública e de entidades privadas que recebam recursos públicos. Assim, o segredo não mais se coaduna com a coisa pública.
                </p>
                <p>
                    Em conformidade com a <a href="http://esic.cge.ro.gov.br/site/anexos/L3166.pdf" target="_blank">Lei Nº. 3.166 DE 27 DE AGOSTO DE 2013</a> c/c <a href="http://esic.cge.ro.gov.br/site/anexos/DECRETO%2017145-2012.pdf" target="_blank">Decreto Nº 17.145/2012</a>, compete à Controladoria Geral do Estado de Rondônia, coordenar e monitorar o Portal da Transparência do Estado de Rondônia.
                </p>
                <p>
                    Seguindo os ditames da LAI, com este Portal da Transparência, o Estado de Rondônia Confere o Cumprimento ao direito fundamental previsto no inciso XXXIII do art. 5º da Constituição Federal, segundo o qual “todos têm direito a receber dos órgãos públicos informações de seu interesse particular, ou de interesse coletivo ou geral”. De igual modo, busca-se implementar o § 7º do art. 37 da Constituição, no ponto em que prevê o acesso a informações privilegiadas, e o art. 216, § 2º, que atribuir à administração pública a gestão da documentação governamental e as providências para franquear sua consulta.
                </p>
                <p>
                    A Lei de Acesso às informações é uma conquista da democracia brasileira, um sinal de civilidade e de participação cidadã da sociedade na condução dos negócios públicos.
                </p>
                <p>
                    Qualquer pessoa, física ou jurídica, pode encaminhar pedidos de acesso a informação para órgãos e entidades do Poder Executivo do Governo do Estado de Rondônia. Para isso basta acessar o e-SIC (Sistema Eletrônico do Serviço de Informações ao Cidadão) no endereço eletrônico <a href="http://esic.cge.ro.gov.br">esic.cge.ro.gov.br</a> ou comparecer ao SIC que fica no TUDO AQUI, localizado na  Avenida Sete de Setembro, 836, Centro 78916-000 - Porto Velho/RO.
                </p>
                <h3>Autoridades responsáveis pelo monitoramento da LAI</h3>
                <ul>
                    <li><strong>Controlador Geral do Estado</strong> - Francisco Lopes Fernandes Netto</li>
                    <li><strong>Coordenadora Transparência Passiva / e-SIC</strong> - Maria Gorete Correa</li>
                    <li><strong>Coordenação Transparência Ativa</strong> - Gerência de Tecnologia da Informação - CGE</li>
                </ul>
            </div>
        </div>
    </div>
</div>

TransparenciaRO.Web/Views/Menu/OPortal.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>O que é o portal</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>O Portal da Transparência é uma iniciativa do Governo do Estado de Rondônia que propicia o controle social pelos cidadãos ao disponibilizar dados e informações públicas do Estado, além de oferecer ferramenta para solicitações de informações por meio da Lei de Acesso a Informação. </p>
            <p>A transparência tem papel importante no combate à corrupção, ao induzir maior responsabilidade por parte dos gestores públicos e controle e divulgação das ações por cidadãos, pesquisadores e mídia. </p>
            <p>O Portal da Transparência contem dados e informações sobre os seguintes assuntos:</p>
            <ul>
                <li>Gastos/despesas públicos dos Poderes do Estado;</li>
                <li>Receitas ou arrecadação dos Poderes do Estado;</li>
                <li>Remuneração dos servidores do Poder Executivo;</li>
                <li>Despesa com pessoal dos Poderes do Estado;</li>
                <li>Despesas com diárias de viagem dos Poderes do Estado;</li>
                <li>Convênios;</li>
                <li>Compras, aquisições e contratos dos Poderes do Estado;</li>
                <li>Planejamento e resultados dos Poderes do Estado;</li>
                <li>Informações socioeconômicas do Estado;</li>
                <li>Prestação de contas do governador;</li>
                <li>Lei de Acesso a Informação</li>
            </ul>
            <h3>Autoridades responsáveis pelo monitoramento da LAI</h3>
            <ul>
                <li><strong>Controlador Geral do Estado</strong> - Francisco Lopes Fernandes Netto</li>
                <li><strong>Coordenadora Transparência Passiva / e-SIC</strong> - Vanessa Trindade de Melo</li>
                <li><strong>Coordenação Transparência Ativa</strong> - Gerência de Tecnologia da Informação - CGE</li>
            </ul>
            <h3>Manual do Portal da Transparência</h3>
            <ul>
                <li><a href="~/Arq/Manual Transparência RO.pdf">Clique aqui para baixar o Manual.</a> </li>
            </ul>
        </div>
    </div>
</div>

TransparenciaRO.Web/Views/Menu/PerguntasFrequentes.cshtml
@using TransparenciaRO.Web.HTMLHelper
@{
    ViewBag.Title = "FAQ - Perguntas Frequentes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Head{
    @Html.RenderizarReferenciasPorPlugin(new[] { EReferenciaHead.Mustache, EReferenciaHead.DataTable })
}
<div class="container" id="faq-container">    
</div>

@section AposFooter{

    <script id="template" type="x-tmpl-mustache">

        {{#perguntas}}
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">{{p}}</h4>
            </div>
            <div class="panel-body">{{r}}</div>
        </div>
        {{/perguntas}}
    </script>

    <script>
        var perguntas = {
            "perguntas": [
                { "p": "O que é o Portal da Transparência?", "r": "O Portal da Transparência é um site do Governo de Rondônia que contém informações acerca das ações governamentais, receitas e despesas do Estado, Lei de Diretrizes Orçamentárias, Plano Plurianual, demonstrativos exigidos pela Lei de Responsabilidade Fiscal, repasse para os Municípios, informações gerenciais, dentre outras informações de interesse dos rondonienses." },
                { "p": "Por que o Portal da Transparência foi criado?", "r": "O Portal da Transparência do Estado de Rondônia foi criado em maio de 2010, com o objetivo de dar mais transparência às ações do governo do Estado. Através dele a sociedade pode acompanhar a correta aplicação dos recursos públicos e evitar que ele seja utilizado de forma indevida. Promover o controle social e o combate à corrupção são os principais objetivos do portal da transparência. Todas as informações estão disponíveis para toda a sociedade, dispensando o uso de cadastro e senha para acessar os dados disponíveis." },
                { "p": "Quais as informações disponíveis no Portal da Transparência?", "r": "No Portal da Transparência o cidadão tem acesso as receitas arrecadas e as despesas realizadas pelo Estado, os repasses aos municípios, as Audiências Publicas realizadas, os gastos do governo por programas, os Relatórios exigidos pela Lei de Responsabilidade Fiscal, Convênios, Contratos, Compras, Licitação entre outras. Para facilitar ainda mais o entendimento, o Portal possui um glossário com a definição de vários termos relacionados à fiscalização e a execução orçamentária e financeira do Estado." },
                { "p": "De onde são obtidos os dados divulgados no portal?", "r": "Os dados orçamentários e financeiros relativos às despesas, às receitas, aos demonstrativos contábeis e fiscais são oriundos do Sistema Integrado de Administração Financeira para Estados e Municípios – SIAFEM, gerenciado pela Secretaria de Estado da Fazenda." },
                { "p": "Qual é a frequência de atualização do Portal da Transparência?", "r": "As informações com relação às receitas e às despesas são atualizadas diariamente. Os relatórios, como por exemplo, os da Lei de Responsabilidade Fiscal, o Plano Plurianual, a Lei de Diretrizes Orçamentárias, a Lei Orçamentária Anual, são atualizados por ocasião de sua divulgação, que pode ser mensal, bimestral, quadrimestral ou anual, conforme determina a legislação vigente." },
                { "p": "Como tirar dúvidas sobre termos, expressões e siglas que aparecem no Portal da Transparência?", "r": "Consulte o Glossário para esclarecimento dos termos técnicos, siglas e demais expressões utilizados nos textos explicativos do Portal da Transparência. Caso você tenha encontrado alguma palavra ou expressão sem definição, ou ainda com definição inconsistente, envie sua sugestão por meio do Fale Conosco." },
                { "p": "O Portal traz informações sobre Fornecedores inidôneos e suspensos, que não podem concorrer às licitações?", "r": "Sim. No menu da página inicial, há a opção \"Fornecedores\", que informa os fornecedores (pessoas jurídicas ou naturais) que sofreram sanções pelos órgãos e entidades da Administração Pública das diversas esferas federativas." },
                { "p": "Tenho dúvidas sobre como consultar a navegação do Portal, o que devo fazer? Como encontrar a informação que estou procurando?", "r": "Consulte o Como Navegar para facilitar a sua navegação no Portal da Transparência do Estado de Rondônia. O objetivo é orientar, de um modo rápido e simples, o cidadão e os agentes públicos a encontrarem as informações desejadas. Por meio deste manual, você recebe instruções simples sobre cada modalidade de consulta existente no Portal da Transparência." },
                { "p": "Quem é obrigado a prestar contas dos recursos públicos?", "r": "Todo aquele que guarde, administre, gerencie, arrecade ou utilize bens e valor público tem o dever constitucional e moral de prestar contas dos recursos públicos. Essa prestação de contas consiste no envio, aos órgãos responsáveis pelo Controle Externo (Assembleia Legislativa e Tribunal de Contas), do conjunto de documentos e informações, obtidos direta ou indiretamente, que permitam avaliar a conformidade e o desempenho da gestão dos responsáveis por políticas públicas, bens, valores e serviços públicos Estaduais." }
            ]
        };
        $(document).ready(function () {
            $('#faq-container').html(Mustache.render($('#template').html(), perguntas));
        });
    </script>
}