TransparenciaRO.Web/Controllers/IndiceController.cs
using System.Linq;
using System.Web.Mvc;
using TransparenciaRO.Infra.DAL;

namespace TransparenciaRO.Web.Controllers
{
    public class IndiceController : ControllerBase
    {
        private readonly DbTransparencia _dbTransparencia = new DbTransparencia();
        private readonly IndiceDAL _indiceDal;

        public IndiceController()
        {
            _indiceDal = new IndiceDAL(_dbTransparencia);
        }

        // GET: Indice
        public ActionResult Index(string pTermosBusca)
        {
            return View(_indiceDal.Buscar(pTermosBusca ?? "").ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _dbTransparencia.Dispose();

            base.Dispose(disposing);
        }
    }
}

TransparenciaRO.Web/Views/Shared/_BuscarSite.cshtml
<form action="@Url.Action("Index","Indice")" method="get" id="frmBusca">
    <div class="col-md-12">
        <script>
            var urlPaginaBusca = '@(Url.Action("Index","Indice"))';
        </script>
        <div class="input-group" id="containerTxtBusca">
            <input type="text" id="pTermosBusca" name="pTermosBusca" class="form-control input-lg" placeholder="Buscar em todo o portal...">
            <a id="btnBusca" class="btn input-group-addon btn-lg" href="#!" onclick="$('#frmBusca').submit();"><i class="glyphicon glyphicon-search"></i></a>
        </div>
    </div>
</form>
<script>
    $('#frmBusca').submit(function (evt) {
        if ($('#pTermosBusca').val().trim() == '')
        {
            alert('Por favor, informe pelo menos um termo de busca');
            evt.preventDefault();
        }

    });
</script>