TransparenciaRO.Web/Controllers/ArquivoController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TransparenciaRO.Infra.DAL;
using TransparenciaRO.Infra.Model.DB.dbTransparencia;
using TransparenciaRO.Infra.Utils;

namespace TransparenciaRO.Web.Controllers
{
    public class ArquivoController : ControllerBase
    {
        private readonly DbTransparencia _dbTransparencia = new DbTransparencia();
        private readonly ArquivoDAL _arquivoDal;
        private readonly PastaDAL _pastaDal;

        public ArquivoController()
        {
            _arquivoDal = new ArquivoDAL(_dbTransparencia);
            _pastaDal = new PastaDAL(_dbTransparencia);
        }

        public ActionResult Adicionar(string pEncPastaId)
        {
            try
            {
                var pastaId = new Guid(CriptografiaUtils.Decrypt(pEncPastaId));
                ViewBag.PastaGuid = pastaId;
                return View();
            }
            catch (Exception exception)
            {
                TempData["Erro"] = exception.Message;
                return RedirectToAction("Index", "Pasta", _pastaDal.BuscarPastas());
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar(HttpPostedFileBase file, Arquivo arquivo, string pEncPastaId)
        {
            try
            {
                if (!ModelState.IsValid) return View(arquivo);

                if (file == null)
                {
                    TempData["Erro"] = "Selecione um arquivo";
                    return View(arquivo);
                }

                var tipoArquivo = Path.GetExtension(file.FileName).ToLower();
                if (ArquivoUtils.ArquivoValido(file))
                {
                    var guidArquivo = Guid.NewGuid();
                    var caminho = Path.Combine(Server.MapPath("~/App_Data/Arquivos"), guidArquivo.ToString());
                    file.SaveAs(caminho);

                    arquivo.ArquivoId = guidArquivo;
                    arquivo.Extensao = tipoArquivo;
                    arquivo.PastaId = new Guid(CriptografiaUtils.Decrypt(pEncPastaId));
                    arquivo.UsuarioIdUpload = AuthenticationManager.User.IdUsuario();

                    _arquivoDal.Adicionar(arquivo);
                    TempData["Sucesso"] = "Arquivo adicionado com sucesso";
                    return RedirectToAction("Index", "Pasta", new { pEncPastaId = CriptografiaUtils.Encrypt(arquivo.PastaId.ToString()) });
                }

                ViewBag.PastaGuid = pEncPastaId.ToDecrypted();
                TempData["Erro"] = "Tipo de arquivo inválido, verique se o arquivo esta no formato PDF ou EXCEL e se possui menos 30MB";
                return View(arquivo);
            }
            catch (Exception exception)
            {
                TempData["Erro"] = exception.Message;
                return RedirectToAction("Index", "Pasta", _pastaDal.BuscarPastas());
            }
        }

        public ActionResult Editar(string pEncArquivoID)
        {
            try
            {
                var arquivoGuid = new Guid(CriptografiaUtils.Decrypt(pEncArquivoID));
                var upload = _arquivoDal.BuscarArquivo(arquivoGuid);
                return View(upload);
            }
            catch (Exception exception)
            {
                TempData["Erro"] = exception.Message;
                return RedirectToAction("Index", "Pasta", _pastaDal.BuscarPastas());
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Guid arquivoId, string descricao, int ordem)
        {
            try
            {
                var arquivo = _dbTransparencia.Arquivos.First(x => x.ArquivoId == arquivoId);
                arquivo.Descricao = descricao;
                arquivo.Ordem = ordem;

                _arquivoDal.Editar(arquivo);
                TempData["Sucesso"] = "Arquivo Alterado com sucesso";
                return RedirectToAction("Index", "Pasta", new { pEncPastaId = CriptografiaUtils.Encrypt(arquivo.PastaId.ToString()) });
            }
            catch (Exception exception)
            {
                TempData["Erro"] = exception.Message;
                return RedirectToAction("Index", "Pasta", _pastaDal.BuscarPastas());
            }
        }

        public ActionResult Remover(string pEncArquivoId)
        {
            try
            {
                var arquivoGuid = new Guid(CriptografiaUtils.Decrypt(pEncArquivoId));
                var upload = _arquivoDal.BuscarArquivo(arquivoGuid);
                return View(upload);
            }
            catch (Exception exception)
            {
                TempData["Erro"] = exception.Message;
                return RedirectToAction("Index", "Pasta", _pastaDal.BuscarPastas());
            }
        }

        [HttpPost, ActionName("Remover")]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmarRemocao(string pEncArquivoId)
        {
            try
            {
                var arquivoGuid = new Guid(CriptografiaUtils.Decrypt(pEncArquivoId));
                var arquivo = _dbTransparencia.Arquivos.First(x => x.ArquivoId == arquivoGuid);
                arquivo.UsuarioIdRemocao = AuthenticationManager.User.IdUsuario();
                _arquivoDal.Remover(arquivo);

                TempData["Sucesso"] = "Arquivo removido com sucesso";
                return RedirectToAction("Index", "Pasta", new { pEncPastaId = CriptografiaUtils.Encrypt(arquivo.PastaId.ToString()) });
            }
            catch (Exception exception)
            {
                TempData["Erro"] = exception.Message;
                return RedirectToAction("Index", "Pasta", _pastaDal.BuscarPastas());
            }

        }

        public ActionResult VisualizarArquivo(string pEncArquivoId)
        {
            try
            {
                var arquivoGuid = new Guid(CriptografiaUtils.Decrypt(pEncArquivoId));
                var arquivo = _arquivoDal.BuscarArquivo(arquivoGuid);
                var bytesArquivo = System.IO.File.ReadAllBytes(ArquivoUtils.CaminhoArquivo(arquivoGuid));
                var mimeType = "application/" + arquivo.Extensao.Replace(".", "");
                Response.AppendHeader("Content-Disposition", "inline; filename=" + arquivo.Descricao.Replace(",", " ") + "." + (arquivo.Extensao.Replace(".", "")));
                return File(bytesArquivo, mimeType);
            }
            catch (Exception exception)
            {
                TempData["Erro"] = exception.Message;
                return RedirectToAction("Index", "Pasta", _pastaDal.BuscarPastas());
            }
        }        

        public FileResult DownloadFile()
        {


            //"~/App_Data/Arquivos"
            string filePath = Server.MapPath("~/App_Data/Arquivos/Licitacoes");
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
            string fileName = "documento.txt";
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _dbTransparencia.Dispose();
            
            base.Dispose(disposing);
        }
    }
}

TransparenciaRO.Web/Controllers/ControleDocumentoExternoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security.Provider;
using TransparenciaRO.Infra.DAL;
using TransparenciaRO.Infra.Enum;
using TransparenciaRO.Infra.Model.DB.dbTransparencia;
using TransparenciaRO.Infra.Utils;
using static TransparenciaRO.Infra.Enum.EPerfilUsuario;

namespace TransparenciaRO.Web.Controllers
{
    public class ControleDocumentoExternoController : ControllerBase
    {
        private readonly DbTransparencia _dbTransparencia = new DbTransparencia();
        private readonly UnidadeGestoraDAL _unidadeGestora;
        private readonly ControleDocumentoExternoDAL _controleDocumentoExternoDal;
        private readonly ArquivoDAL _arquivoDal;
        public ControleDocumentoExternoController()
        {
            _unidadeGestora = new UnidadeGestoraDAL(_dbTransparencia);
            _controleDocumentoExternoDal = new ControleDocumentoExternoDAL(_dbTransparencia);
            _arquivoDal = new ArquivoDAL(_dbTransparencia);
        }


        // GET: ControleDocumentoExterno

        [Authorize(Roles = nameof(AdministradorControleDocumentoExterno))]
        public ActionResult Index()
        {
            ViewBag.UnidadeGestora = _unidadeGestora.UnidadesGestorasDictionary();
            return View();
        }

        [Authorize(Roles = nameof(AdministradorControleDocumentoExterno))]
        public ActionResult Novo()
        {
            ViewBag.UnidadeGestora = _unidadeGestora.UnidadesGestorasDictionary();
            return View(new ControleDoumentoExterno());
        }

        [Authorize(Roles = nameof(AdministradorControleDocumentoExterno))]
        public ActionResult Editar(string documentoId)
        {
            using (var dbTransparencia = new DbTransparencia())
            {
                ViewBag.UnidadeGestora = _unidadeGestora.UnidadesGestorasDictionary();
                var controleDocumentoExterno = _controleDocumentoExternoDal.Buscar(new Guid(documentoId));
                if (controleDocumentoExterno == null)
                {
                    MensagemErro = "Número de processo / documento informado inválido";
                }
                return View(controleDocumentoExterno);
            }
        }
        [Authorize(Roles = nameof(AdministradorControleDocumentoExterno))]
        public ActionResult Detalhar(string documentoId)
        {
            using (var dbTransparencia = new DbTransparencia())
            {
                ViewBag.UnidadeGestora = _unidadeGestora.UnidadesGestorasDictionary();
                var controleDocumentoExterno = _controleDocumentoExternoDal.Buscar(new Guid(documentoId));
                if (controleDocumentoExterno == null)
                {
                    MensagemErro = "Número de processo / documento informado inválido";
                }
                return View(controleDocumentoExterno);
            }
        }

        public ActionResult AdicionarArquivo(ControleDoumentoExterno dados)
        {
            var msgErrosArquivos = new List<String>();
            for (var i = 0; i < Request.Files.Count; i++)
            {
                if (ArquivoUtils.ArquivoValido(Request.Files[i]))
                {
                    //Novos arquivos (salva no disco e BD)
                    var novoArquivo = new Arquivo();
                    novoArquivo.ArquivoId = Guid.NewGuid();
                    novoArquivo.ControleDoumentoExternoId = dados.ControleDoumentoExternoId == new Guid() ? null : (Guid?)dados.ControleDoumentoExternoId;
                    novoArquivo.UsuarioIdUpload = AuthenticationManager.User.IdUsuario();
                    novoArquivo.Extensao = Path.GetExtension(Request.Files[i].FileName);
                    novoArquivo.Descricao = Request.Files[i].FileName;
                    novoArquivo.PastaId = GuidUtils.GuidPastaContratosEConvenios();
                    novoArquivo.Temporario = true; //Arquivos com esta propriedade serão excluídos automaticamente por uma rotina de varredura diária no servidor
                    if (ArquivoUtils.SalvarArquivo(Request.Files[i], novoArquivo.ArquivoId))
                    {
                        _arquivoDal.Adicionar(novoArquivo);
                        dados.Arquivos.Add(novoArquivo);
                    }
                    else
                    {
                        msgErrosArquivos.Add($"Não foi possível fazer o upload do arquivo devido a um erro interno do sistema. Contate o administrador do sistema.");
                    }
                }
                else
                {
                    msgErrosArquivos.Add($"Não foi possível fazer o upload do arquivo {Request.Files[i].FileName}. Verifique se o mesmo possui menos de 10MB e uma das seguintes extensões: PDF, XLS, XLSX, DOC ou DOCX");
                }
            }
            ViewBag.MensagensErrosArquivos = msgErrosArquivos;
            return PartialView("_ListaArquivos", dados);
        }

        public ActionResult RemoverArquivo(ControleDoumentoExterno dados, string guidArquivo)
        {
            if (ArquivoUtils.ArquivoExiste(new Guid(guidArquivo)) && dados.ControleDoumentoExternoId != new Guid())
            {
                //Foi solicitada a exclusão de um arquivo de uma licitação já cadastrada no BD. Nada será feito agora. Apenas na hora de salvar a portaria, onde será comparado o BD com a lista atual
            }
            else if (ArquivoUtils.ArquivoExiste(new Guid(guidArquivo)))
            {
                //Arquivo ainda é temporário, poderá ser excluído fisicamente do disco (ainda não existe na base)
                ArquivoUtils.ExcluirArquivo(new Guid(guidArquivo));
            }
            //Remove do array de arquivos que está sendo utilizado pela view
            dados.Arquivos.Remove(dados.Arquivos.FirstOrDefault(a => a.ArquivoId == new Guid(guidArquivo)));
            //Devolve à view  o modelo atualizado (apenas a Partial _ListaArquivos.cshtml será renderizada novamente, e apenas a propriedade Arquivos acessada)
            return PartialView("_ListaArquivos", dados);
        }


        //POST
        [HttpPost]
        public ActionResult Novo(ControleDoumentoExterno dados)
        {
            dados.ETipoStatus = ETipoStatus.EmPrazo;
            try
            {
                if (!ModelState.IsValid)
                {
                    MensagemErro = "Dados inválidos. Por favor, verifique o cadastro";
                    ViewBag.UnidadeGestora = _unidadeGestora.UnidadesGestorasDictionary();
                    return View(dados);
                }

                var msgErro = "";
                var guid = _controleDocumentoExternoDal.AdicionarEditar(dados, out msgErro);
                if (msgErro != "")
                {
                    MensagemErro = msgErro;
                    return RedirectToAction("Index");
                }

                MensagemSucesso = $"Documento salvo com sucesso!";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                MensagemErro = $"Ocorreu um erro inesperado: ''. Caso o problema persista, entre em contato com a CGE";
                return View("Index");
            }
        }

        [HttpPost]
        public ActionResult Finalizar(string documentoExternoId)
        {
            var documentoGuid = new Guid();
            documentoGuid = new Guid(documentoExternoId);

            ControleDoumentoExterno controleDoumentoExterno = new ControleDoumentoExterno();
            controleDoumentoExterno = _controleDocumentoExternoDal.BuscarPorId(documentoGuid);
            controleDoumentoExterno.DataFinalizacao = DateTime.Now;
            controleDoumentoExterno.ETipoStatus = ETipoStatus.Finalizado;
            _controleDocumentoExternoDal.Update(controleDoumentoExterno);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult ProrrogarPrazo(string documentoExternoIdProrrogado, int diasProrrogado)
        {
            var documentoGuid = new Guid();
            documentoGuid = new Guid(documentoExternoIdProrrogado);

            ControleDoumentoExterno controleDoumentoExterno = new ControleDoumentoExterno();
            controleDoumentoExterno = _controleDocumentoExternoDal.BuscarPorId(documentoGuid);
            controleDoumentoExterno.ProrrogacaoDePrazo = diasProrrogado;
            _controleDocumentoExternoDal.Update(controleDoumentoExterno);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Editar(ControleDoumentoExterno dados)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    MensagemErro = "Dados inválidos. Por favor, verifique o cadastro";
                    ViewBag.UnidadeGestora = _unidadeGestora.UnidadesGestorasDictionary();
                    return View(dados);
                }

                var msgErro = "";
                var guid = _controleDocumentoExternoDal.AdicionarEditar(dados, out msgErro);
                if (msgErro != "")
                {
                    MensagemErro = msgErro;
                    return RedirectToAction("Index");
                }

                MensagemSucesso = $"Documento salvo com sucesso!";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                MensagemErro = $"Ocorreu um erro inesperado: ''. Caso o problema persista, entre em contato com a CGE";
                return View("Index");
            }
        }

        //JSON

        public JsonResult Consultar(string numeroDocumento, string unidadeGestora)
        {
            var tabela = _controleDocumentoExternoDal.BuscarDocumento(numeroDocumento, unidadeGestora)
                .Select(x => new
                {
                    documentoId = x.ControleDoumentoExternoId,

TransparenciaRO.Web/Views/ControleDocumentoExterno/Index.cshtml
@using TransparenciaRO.Web.HTMLHelper

@{
    @Html.RenderizarReferenciasPorPlugin(new[] { EReferenciaHead.Mustache, EReferenciaHead.DataTable })
}

@section Head
{
    <link href="~/Content/bootstrap-chosen.css" rel="stylesheet" />
}
<div class="row margin-bottom-15px">
    <div class="col-md-12">
        <div class="pull-right">
            <a href="@Url.Action("Novo")" class="btn btn-lg btn-primary">Novo</a>
        </div>
    </div>
</div>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Controle de Prazo</h3>
    </div>
    <div class="panel-body">
        <div id="divConsulta">
            <div class="col-md-5">
                <div class="col-md-12 col-sm-12 form-group">
                    <label>Nº Processo / Documento</label>
                    <input type="text" name="numeroDocumento" id="numeroDocumento" class="form-control" />
                </div>
                <div class="col-md-12 col-sm-12 form-group">
                    <label>Secretaria</label>
                    @Html.DropDownList("secretaria", new SelectList(ViewBag.UnidadeGestora, "Key", "Value"), "Todos", new { @class = "form-control" })

                </div>
            </div>
            <div class="col-md-7">
                <div class="row">
                    <div class="loadingPlaceholder">
                        <h2 class="text-center">
                            <i class="fa fa-cog fa-spin"></i>&nbsp;Processando gráfico...
                        </h2>
                    </div>

                    <div id="grafico" class="grafico col-md-12" style="height: 250px"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <button id="btnConsultar" class="btn btn-primary">Consultar</button>
    </div>
</div>

<div id="containerTabela"></div>


<div class="modal fade" id="myModalFinalizar" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Responder Fiscalização</h4>
            </div>
            @using (Html.BeginForm("Finalizar", "ControleDocumentoExterno", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="modal-body">
                    <input type="hidden" id="documentoExternoId" name="documentoExternoId" value="" />
                    <div class="form-group">
                        <p>Deseja Finalizar este Documento?</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Sim</button>
                </div>
            }
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="myModalProrrogado" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Responder Fiscalização</h4>
            </div>
            @using (Html.BeginForm("ProrrogarPrazo", "ControleDocumentoExterno", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="modal-body">
                    <input type="hidden" id="documentoExternoIdProrrogado" name="documentoExternoIdProrrogado" value="" />
                    <div class="form-group">
                        <label>Dias Para Prorrogar o Prazo</label>
                        <input type="text" name="diasProrrogado" id="diasProrrogado" class="form-control" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Enviar</button>
                </div>
            }
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
<!-- /.modal -->

@section AposFooter
{
    <script src="~/scripts/chosen.jquery.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script>
        $('.input-daterange').datepicker({
            format: "dd/mm/yyyy",
            language: "pt-BR",
            autoclose: true
        });

        $(document).ready(() => {
            $("#secretaria").chosen();
        });

    </script>


    <script type="text/html" id="templateTabela">
        <div class="row">
            <div class="col-md-12 col-lg-12 table-responsive">
                <table id="tabelaDemandas" class="table" width="100%">
                    <thead>
                        <tr>
                            <th>Nº Processo / Documento</th>
                            <th>Orgão de Origem</th>
                            <th>Data de Abertura</th>
                            <th>Prazo</th>
                            <th>Dias Prorrogado</th>
                            <th>Data de Finalização</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {{#dados}}
                        <tr class="{{CorLinha}}">
                            <td>{{NumeroProcessoDocumento}}</td>
                            <td>{{OrgaoOrigem}}</td>
                            <td>{{DataAbertura}}</td>
                            <td>{{Prazo}}</td>
                            <td>{{ProrrogacaoPrazo}}</td>
                            <td>{{DataFinalizacao}}</td>
                            <td>{{Status}}</td>
                            <td>
                                <a href="@Url.Action("Detalhar")?documentoId={{documentoId}}" class="btn btn-default btn-block">Detalhes</a>
                                <button id="btnFinalizar" class="btn btn-success btn-block" data-toggle="modal" data-target="#myModalFinalizar" onclick="PreencherIdNoModal('{{documentoId}}')">Finalizar</button>
                                <button class="btn btn-primary btn-block" data-toggle="modal" data-target="#myModalProrrogado" onclick="PreencherIdNoModalProrrogar('{{documentoId}}')">Prorrogar</button>
                                <a href="@Url.Action("Editar")?documentoId={{documentoId}}" class="btn btn-warning btn-block">Editar</a>
                            </td>
                        </tr>
                        {{/dados}}
                        {{^dados}}
                        <tr>
                            <td colspan="4" class="text-center">Nenhum registro encontrado</td>
                        </tr>
                        {{/dados}}
                    </tbody>
                </table>
            </div>
        </div>
    </script>



    <script>

        function carregarGrafico(categorias, name, title, xAxis, yAxis) {
            Highcharts.setOptions({
                lang: {
                    numericSymbols: [' mil', ' milhões']
                }
            });
            $('#grafico')
                .highcharts({
                    chart: {
                        type: 'column'
                    },
                    title: {
                        text: title
                    },
                    xAxis: {
                        type: "category",
                        title: {
                            text: '<b>' + xAxis + '</b>'
                        }
                    },
                    yAxis: {
                        title: {
                            text: '<b>' + yAxis + '</b>'
                        },
                        labels: {
                            //format: '{value:.2f}'

                        }
                    },
                    legend: {
                        enabled: false
                    },
                    plotOptions: {
                        series: {
                            borderWidth: 0,
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    tooltip: {
                        headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                        pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y}</b><br/>'
                    },
                    series: [
                        {
                            name: name,
                            colorByPoint: true,
                            data: categorias
                        }
                    ]
                });
        }

    </script>
    <script>

        $(document).ready(() => {
            processarTabela();
        });

        $('#btnConsultar').on('click',
            () => {
                processarTabela();
                processarGrafico();
            });

            function PreencherIdNoModal(id) {
                    $('#documentoExternoId').val(id);
            };
            function PreencherIdNoModalProrrogar(id) {
                $('#documentoExternoIdProrrogado').val(id);
            };

        function processarTabela() {
            $("#containerTabela")
                .html('<label name="spin" class="hidden"><i class="fa fa-cog fa-spin fa-fw"></i> Carregando...</label>');

            $.get('@Url.Action("Consultar", "ControleDocumentoExterno")',
                {
                    numeroDocumento: $('#numeroDocumento').val(),
                    unidadeGestora: $('#secretaria').val()
                }).done(function (dados) {


                    var htmlRenderizado = Mustache.render($('#templateTabela').html(), { "dados": dados.tabela });

                    processarGrafico(dados.grafico);
                    $('#containerTabela').html(htmlRenderizado);
                    $("#tabelaDemandas").dataTablePadrao();
            });
        }

        function processarGrafico(grafico) {
                var status = [];
                for (var i = 0; i < grafico.length; i++) {

                    if (grafico.length > i) {
                        var serie = { name: grafico[i].Descricao, y: grafico[i].Qtd, color: grafico[i].color, drilldown: false };
                        status.push(serie);
                    }

                carregarGrafico(status, "Status", "Documentos", "", "");
                $('.loadingPlaceholder > h2').fadeOut('slow');
                $("#grafico").fadeIn('slow');
            };
        }
    </script>
}

TransparenciaRO.Web/Views/ControleDocumentoExterno/_ListaArquivos.cshtml
@using TransparenciaRO.Infra.Model.DB.dbTransparencia
@using TransparenciaRO.Infra.Utils
@model ControleDoumentoExterno
@{
    var MensagensErrosArquivos = ViewBag.MensagensErrosArquivos as List<String>;
}
@if (MensagensErrosArquivos?.Count > 0)
{
    foreach (var mensagemErro in MensagensErrosArquivos)
    {
        <div class="alert alert-danger">@mensagemErro</div>
    }
}
@if (Model.Arquivos.Count > 0)
{

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nome do arquivo</th>
            @if (User.Identity.IsAuthenticated)
            {
                <th id="thExcluir">Excluir?</th>
            }
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Arquivos.Count; i++)
            {
                <tr>
                    <td>
                        <input type="hidden" name="Arquivos[@i].ArquivoId" value="@Model.Arquivos.ToList()[i].ArquivoId.ToString()" />
                        <input type="hidden" name="Arquivos[@i].LicitacaoId" value="@Model.Arquivos.ToList()[i].ControleDoumentoExternoId.ToString()" />
                        <input type="hidden" name="Arquivos[@i].Descricao" value="@Model.Arquivos.ToList()[i].Descricao" />
                        <input type="hidden" name="Arquivos[@i].Temporario" value="@(Model.Arquivos.ToList()[i].Temporario ? "true" : "false")" />
                        <a href="@Url.Action("VisualizarArquivo", "Arquivo", new { pEncArquivoId = Model.Arquivos.ToList()[i].ArquivoId.ToString().ToEncrypted()  })" target="_blank">@(Model.Arquivos.ToList()[i].Descricao)</a>
                    </td>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <td><a href="#!" class="btn btn-danger btn-excluir-arquivo" data-dados-arquivo='{"guidArquivo":"@Model.Arquivos.ToList()[i].ArquivoId.ToString()","NomeArquivo":"@Model.Arquivos.ToList()[i].Descricao"}'><i class="fa fa-trash"></i> Excluir</a></td>
                    }
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info">Nenhum arquivo adicionado</div>
}