TransparenciaRO.Web/Controllers/GraficoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TransparenciaRO.Infra.Enum;
using TransparenciaRO.Infra.Model.View;
using TransparenciaRO.Infra.Utils;
using TransparenciaRO.Infra.DAL;
using System.Globalization;
using TransparenciaRO.Infra.Model.DB.dbTransparencia;
using System.Text;

namespace TransparenciaRO.Web.Controllers
{
    public class GraficoController : ControllerBase
    {
        private readonly DbTransparencia _dbTransparencia = new DbTransparencia();
        private readonly DespesaDAL _despesaDal;
        private readonly UnidadeGestoraDAL _unidadeGestoraDal;
        private readonly ParametrosDAL _parametrosDal;
        private readonly OrgaoDAL _orgaoDal;
        private readonly ModalidadeLicitacaoDAL _modalidadeLicitacaoDal;
        private readonly ViewEmpenhosDal _viewEmpenhosDal;
        private readonly MateriaisDAL _materiaisDAL;

        public GraficoController()
        {
            _despesaDal = new DespesaDAL(_dbTransparencia);
            _unidadeGestoraDal = new UnidadeGestoraDAL(_dbTransparencia);
            _parametrosDal = new ParametrosDAL(_dbTransparencia);
            _orgaoDal = new OrgaoDAL(_dbTransparencia);
            _modalidadeLicitacaoDal = new ModalidadeLicitacaoDAL(_dbTransparencia);
            _viewEmpenhosDal = new ViewEmpenhosDal(_dbTransparencia);
            _materiaisDAL = new MateriaisDAL(_dbTransparencia);
        }

        #region Receita

        public ActionResult Receita()
        {
            // Por padrão, irá listar os últimos 5 anos, consolidado por ano, e a receita total (sem tributos).
            // Estes parâmetros poderão ser mudados diretamente na tela
            //var dadosReceitaArrecadada = ReceitaBusiness.GetReceita(DateTime.Now.AddYears(-4).Year, DateTime.Now.Year, ETipoConsolidacao.PorAno, ETipoConsultaReceita.Total, null, true);
            ViewBag.UnidadesGestoras = _unidadeGestoraDal.GetUnidadesGestoras().Where(ug => ug.unidadeGestoraIDSIAFEM != null).ToList();
            ViewBag.DataAtualizacao = _parametrosDal.GetParametro(ETipoParametro.DataAtualizacaoReceita);

            return View();
        }

        #endregion

        #region Despesas
        [HttpPost]
        public JsonResult ExibirDespesas(int pCodUnidadeGestora, string pNumeroEmpenho, string pNomeCredor, string pDocCredor)
        {
            var mostrarTodosAnos = GetPermissoesUsuario().Contains(EPerfilUsuario.VisualizacaoCompletaDespesas);
            return Json(_despesaDal.GetDespesasPorAno(pCodUnidadeGestora, pNumeroEmpenho, pNomeCredor, pDocCredor.Replace("-", "").Replace("/", "").Replace(".", ""), !mostrarTodosAnos));
        }

        public JsonResult DetalharDespesa(string pEncParametros)
        {
            var parametros = pEncParametros.ToParametrosDetalharDespesaModel();

            if (parametros == null)
                return Json(null);
            switch (parametros.TipoDetalhamentoDespesa)
            {
                case ETipoDetalhamentoDespesa.DespesasMeses:
                    return Json(_despesaDal.GetDespesasMeses(parametros.CodUnidadeGestora, parametros.Exercicio, parametros.NumeroEmpenho, parametros.NomeCredor, parametros.DocCredor), JsonRequestBehavior.AllowGet);
                case ETipoDetalhamentoDespesa.DespesasProgramaAcao:
                    return Json(_despesaDal.GetDespesasProgramaAcao(parametros.MesAno, parametros.CodUnidadeGestora, parametros.NumeroEmpenho, parametros.NomeCredor, parametros.DocCredor), JsonRequestBehavior.AllowGet);
                case ETipoDetalhamentoDespesa.DespesasFuncoes:
                    return Json(_despesaDal.GetDespesasFuncoes(parametros.MesAno, parametros.CodUnidadeGestora, parametros.CodPrograma, parametros.CodAcao, parametros.CodProjeto, parametros.NumeroEmpenho, parametros.NomeCredor, parametros.DocCredor), JsonRequestBehavior.AllowGet);
                case ETipoDetalhamentoDespesa.DespesasNaturezas:
                    return Json(_despesaDal.GetDespesasNaturezas(parametros.MesAno, parametros.CodUnidadeGestora, parametros.CodPrograma, parametros.CodAcao, parametros.CodProjeto, parametros.CodFonteRecursos, parametros.NumeroEmpenho, parametros.NomeCredor, parametros.DocCredor), JsonRequestBehavior.AllowGet);
                case ETipoDetalhamentoDespesa.DespesasEmpenhos:
                    return Json(_despesaDal.GetDespesasEmpenhos(parametros.MesAno, parametros.CodUnidadeGestora, parametros.CodPrograma, parametros.CodAcao, parametros.CodProjeto, parametros.CodFonteRecursos, parametros.CodEspecificacaoDespesa, parametros.NumeroEmpenho, parametros.NomeCredor, parametros.DocCredor), JsonRequestBehavior.AllowGet);
                default:
                    return Json(null);
            }
        }

        public ActionResult Despesa()
        {
            var DataInicial = DateTime.Now.AddMonths(-1).ToString("MM-yyyy");
            var DataFinal = DateTime.Now.ToString("MM-yyyy");
            ViewBag.DataInicial = DataInicial;
            ViewBag.DataFinal = DataFinal;
            ViewBag.UnidadesGestoras = _unidadeGestoraDal.GetUnidadesGestoras();
            ViewBag.DataAtualizacao = _parametrosDal.GetParametro(ETipoParametro.DataAtualizacaoDespesas);
            return View();
        }
        #endregion

        #region Dotação Inicial
        public ActionResult DotacaoInicial()
        {
            ViewBag.UnidadesGestoras = _orgaoDal.GetOrgaosConsolidadosPorNome()
                   .Union(new Dictionary<string, string> { { "0", "TODOS" } }).OrderBy(o => o.Key).ToDictionary(k => k.Key, v => v.Value);

            ViewBag.DataAtualizacao = _parametrosDal.GetParametro(ETipoParametro.DataAtualizacaoDotacaoInicial);

            return View();
        }

        [HttpPost]
        public JsonResult DotacaoInicial(int pExercicio, string pUG)
        {
            var ugs = pUG.Split(',').Distinct().Select(ug => ug.PadLeft(6, '0'));

            var retorno = _dbTransparencia.DotacaoInicial
                 .Where(di => di.Exercicio == pExercicio && (pUG == "0" || ugs.Contains(di.CodigoOrgao)))
                 .Take(1000)
                 .ToList()
                 .Select(di => new { di.CodigoOrgao, di.Exercicio, di.NaturezaDespesa, di.DescricaoDespesa, di.Orgao, di.ProgramaTrabalho, SaldoInicial = di.SaldoInicial.ToString("c2") })
                 .ToList();

            return Json(new DadosTabuladosGenericosModel { dados = retorno, msgInformacao = retorno.Count == 1000 ? "Apenas os 1000 primeiros registros serão exibidos" : null });
        }
        #endregion

        #region Compras e contratações
        public class ParametrosComprasContratacoesModel
        {
            public DateTime pDataInicial { get; set; }
            public DateTime pDataFinal { get; set; }
            public string CodUnidadeGestora { get; set; }


            private int _codModalidadeCompra;
            public int? CodModalidadeCompra
            {
                get => _codModalidadeCompra == 0 ? null : (int?)_codModalidadeCompra;
                set => _codModalidadeCompra = value ?? 0;
            }

        }

        public ActionResult DetalhesEmpenho(string numeroEmpenho, string unidadeGestora)
        {
            ViewBag.UnidadesGestora = _orgaoDal.GetOrgaos().Where(o => o.CodOrgao == unidadeGestora.ToDecrypted().PadLeft(6, '0').ToInt()).FirstOrDefault();
            return View(_viewEmpenhosDal.GetDetalhesEmpenho(numeroEmpenho, unidadeGestora.ToDecrypted().PadLeft(6, '0')));
        }

        public ActionResult DetalhesEmpenhoCOVID19(string numeroEmpenho, string unidadeGestora)
        {
            ViewBag.UnidadesGestora = _orgaoDal.GetOrgaos().Where(o => o.CodOrgao == unidadeGestora.ToInt()).FirstOrDefault();

            return View("DetalhesEmpenho", _viewEmpenhosDal.GetDetalhesEmpenho(numeroEmpenho, unidadeGestora));
        }

        public ActionResult ComprasContratacoes()
        {
            var parametros = new ParametrosComprasContratacoesModel();
            ViewBag.UnidadesGestoras = _orgaoDal.GetOrgaos().Select(org => new { NomOrgao = org.NomOrgao.Trim(), CodOrgao = org.CodOrgao }).Distinct().GroupBy(org => org.NomOrgao).Select(org => new SelectOptionModel(String.Join(",", org.Select(o => o.CodOrgao).ToArray()), org.Key)).Combify("Selecione...").ToList();
            ViewBag.ModalidadesCompra = _modalidadeLicitacaoDal.GetModalidades().Select(m => new SelectOptionModel(m.Codigo.ToString(), m.Descricao)).Combify("Selecione...").ToList();
            ViewBag.Parametros = parametros;
            ViewBag.DataAtualizacao = _parametrosDal.GetParametro(ETipoParametro.DataAtualizacaoComprasContratacoes);
            return View();
        }


        [HttpPost]
        public JsonResult ComprasContratacoes(string pEncListaUnidadeGestora, string pEncCodModalidadeCompra, string pEmpenho, string pDataInicial, string pDataFinal)
        {
            if (pEncListaUnidadeGestora == null || pEncCodModalidadeCompra == null)
            {
                return Json(new { msgInfo = "Por favor, preencha os campos obrigatórios" });
            }

            var pCodModalidadeCompra = Convert.ToInt32(pEncCodModalidadeCompra.ToDecrypted());
            var lstOrgaos = pEncListaUnidadeGestora.ToDecrypted().Split(',').ToList();
            var numEmpenho = pEmpenho;
            const int MaxRegistros = 1000;
            string codUG;

            codUG = pEncListaUnidadeGestora.ToDecrypted();

            var dtInicial = (string.IsNullOrEmpty(pDataInicial) ? (DateTime?)null : Convert.ToDateTime(pDataInicial).Date);
            var dtFinal = (string.IsNullOrEmpty(pDataFinal) ? (DateTime?)null : Convert.ToDateTime(pDataFinal).Date);
            int codMod = pCodModalidadeCompra == 0 ? 0 : pCodModalidadeCompra;

            var data = _viewEmpenhosDal
                .GetComprasContratacoes(pCodModalidadeCompra, codUG, pDataInicial, pDataFinal, numEmpenho)
                .ToList();

            return Json(new
            {

TransparenciaRO.Web/Views/Grafico/ComprasContratacoes.cshtml
@using TransparenciaRO.Infra.Model.View
@using TransparenciaRO.Infra.Utils
@using TransparenciaRO.Web.Controllers
@using TransparenciaRO.Web.HTMLHelper

@{
    ViewBag.Title = "Compras e contratações";
    var unidadesGestoras = (List<SelectOptionModel>)ViewBag.UnidadesGestoras;
    var modalidadesCompras = (List<SelectOptionModel>)ViewBag.ModalidadesCompra;
    var parametros = (GraficoController.ParametrosComprasContratacoesModel)ViewBag.Parametros;
}

@section Head{
    @Html.RenderizarReferenciasPorPlugin(new[] { EReferenciaHead.Mustache, EReferenciaHead.DataTable })
}

<div class="alert alert-default alert-dismissible text-primary" role="alert" style="background-color:#f5f5f5; border-color:#cccccc">
    <i class="fa fa-info-circle"></i>
    <strong>Atenção: </strong> Os asteriscos (<span class="text-danger">*</span>) referem-se aos campos de preenchimento obrigatório.
</div>

<div>
    <form>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="cboUnidadeGestora"><em class="text-danger">* </em>Unidade gestora:</label><br />
                            <select id="cboUnidadeGestora" class="form-control cboSelectFiltro">
                                @foreach (var ug in unidadesGestoras)
                                {
                                    <option value="@ug.Codigo" @(Request["ug"] != null && Request["ug"].PadLeft(6, '0') == ug.Codigo.ToDecrypted().PadLeft(6, '0') ? "selected" : "")>@ug.Descricao</option>
                                }
                            </select>
                            <input type="hidden" id="empenho" name="empenho" value="@Request["pEmpenho"]" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="cboModalidadeCompra"><em class="text-danger">* </em>Modalidade da compra:</label><br />
                            <select id="cboModalidadeCompra" class="form-control cboSelectFiltro">
                                @foreach (var mc in modalidadesCompras)
                                {
                                    <option value="@mc.Codigo">@mc.Descricao</option>
                                }
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="txtDataInicial">Data inicial:</label><br />
                            <div class="input-daterange input-group" id="periodo">
                                <input id="dataInicial" name="dataInicial" type="text" class="form-control" value="" />
                                <span class="input-group-addon">a</span>
                                <input type="text" class="form-control" name="end" id="dataFinal" value="" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-12">
                        <button type="button" class="btn btn-primary" onclick="exibirComprasContratacoes(10,1);">Consultar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    @if (!String.IsNullOrWhiteSpace(ViewBag.DataAtualizacao))
    {
        <div class="container chartFooter">* Última atualização de compras e contratações: <b>@DateTime.Parse(ViewBag.DataAtualizacao.ToString()).ToString("dd/MM/yyyy")</b> / Fonte dos dados: SIAFEM / SUPER</div>
    }

    <div class="row">
        <div class="col-md-12">
            <div class="container-fluid" id="tabelaDadosContainer">
            </div>
        </div>

    </div>
</div>
@section AposFooter{
    <script>
        $(document).ready(function () {
            $('.input-daterange').datepicker({
                language: "pt-BR",
                format: "dd-mm-yyyy"
            });
            //exibirComprasContratacoes(10, 1);
        });

        function exibirComprasContratacoes(pageSize, pageNumber) {
            let dataInicial = $('#dataInicial').datepicker('getDate'),
                dataFinal = $('#dataFinal').datepicker('getDate');

            $('#tabelaDadosContainer').html('<i class="fa fa-cog fa-spin"></i> Carregando dados...');
            $('#dataInicial').datepicker('hide');
            $('#dataFinal').datepicker('hide');
            $.post('/Grafico/ComprasContratacoes', {
                pDataInicial: dataInicial == null ? dataInicial : dataInicial.toYMD(),
                pDataFinal: dataFinal == null ? dataFinal : dataFinal.toYMD(),
                pEncListaUnidadeGestora: $('#cboUnidadeGestora').val(),
                pEncCodModalidadeCompra: $('#cboModalidadeCompra').val(),
                pEmpenho: $('#empenho').val(),
                pPageSize: pageSize,
                pPageNumber: pageNumber
            })
                .done(function (data) {
                    if (data.msgErro != null) {
                        $('#tabelaDadosContainer').html('<div class="alert alert-warning" role="alert"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><span class="sr-only">Erro:</span>' + data.msgErro + '</div>');
                    }
                    else {
                        data.dados = data.dados.map((item) => {
                            item.DataDocumento = parseDate(item.DataDocumento);
                            item.ValorTotal = "R$ " + parseFloat(item.ValorEmpenhada).toFixed(2).replace(".", ",");
                            return item;
                        });
                        $('#tabelaDadosContainer').html(Mustache.render($('#templateDados').html(), data));
                        $('#tabelaDadosContainer > #tabelaDados').dataTablePadrao({ "colunasFixas": 1 });
                        if (data.msgInfo != null) {
                            $('#tabelaDadosContainer').prepend('<div class="alert alert-info" role="alert"><span class="sr-only">Informação:</span><strong>Informação </strong>' + data.msgInfo + '</div>');
                        }
                    }
                })
                .fail(function () {
                    $('#tabelaDadosContainer').html('<div class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><span class="sr-only">Erro:</span><strong>Erro: </strong>Ocorreu um erro ao efetuar a pesquisa. Caso o problema persista, entre em contato com a CGE através do e-mail <a href="mailto:contato@cge.ro.gov.br">contato@cge.ro.gov.br</a>.</div>');
                });
        }
    </script>
    <script id="templateDados" type="text/html">
        <table class="table table-striped" id="tabelaDados">
            <thead>
                <tr>
                    <th> Detalhar</th>
                    <th>Nº empenho</th>
                    <th>Credor</th>
                    <th>Processo</th>
                    <th>Tipo</th>
                    <th>Mod. Compra</th>
                    <th>Data Empenho</th>
                    <th>Vlr. Total</th>
                    <th> Status</th>

                </tr>
            </thead>
            <tbody>
                {{#dados}}
                <tr>
                    <td>
                        <a href="javascript:void(0);" onclick="detalhesEmpenho('@(Url.Action("DetalhesEmpenho", "Grafico"))?NumeroEmpenho={{ NumeroEmpenho }}')">
                            <i class="glyphicon glyphicon-search"> </i>
                        </a>
                    </td>
                    <td><b>{{NumeroEmpenho}}</b></td>
                    <td>{{Credor}}</td>
                    <td>{{NumeroProcesso}}</td>
                    <td>{{TipoEmpenho}}</td>
                    <td>{{ModalidadeCompra}}</td>
                    <td>{{DataDocumento}}</td>
                    <td>{{ValorTotal}}</td>
                    <td>{{Status}}</td>
                </tr>
                {{/dados}}
            </tbody>

            <tfoot>
                <tr>
                    <th>Detalhar</th>
                    <th>Nº empenho</th>
                    <th>Credor</th>
                    <th>Processo</th>
                    <th>Tipo</th>
                    <th>Mod. Compra</th>
                    <th>Data Empenho</th>
                    <th>Vlr. Total</th>
                    <th>Status</th>
                </tr>
            </tfoot>
        </table>
    </script>

    <link href="~/Content/bootstrap-chosen.css" rel="stylesheet" />
    <script src="~/scripts/chosen.jquery.min.js"></script>
    <script>

       
        function parseDate(date) {
            return new Date(Number(date.match(/(\d)+/)[0])).toLocaleString().split(" ")[0];
        }

        $(document).ready(function () {
            $(document).ready(function () {
                $(".cboSelectFiltro").chosen();

                if ($('#cboUnidadeGestora').val() !== 'QMR4ZdomqcS83Fb3ZT3aeA3QU4L3QU4L' && $('#cboModalidadeCompra').val() !== 'QMR4ZdomqcS83Fb3ZT3aeA3QU4L3QU4L') {
                    exibirComprasContratacoes(10, 1);
                }
            });
        });

        function detalhesEmpenho(url) {
            window.location.href = window.location.origin + url + '&unidadeGestora=' + $('#cboUnidadeGestora').val();
        }
    </script>
}

TransparenciaRO.Web/Views/Grafico/ComprasMateriais.cshtml
@using TransparenciaRO.Infra.Model.DB.dbTransparencia
@using TransparenciaRO.Web.HTMLHelper

@{
    ViewBag.Title = "Compras de materiais de consumo e permanente";
}

@section Head{
    @Html.RenderizarReferenciasPorPlugin(new[] { EReferenciaHead.Mustache, EReferenciaHead.DataTable })
}

<form>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="cboUnidadeGestora">Unidade gestora:</label><br />
                        <select id="cboUnidadeGestora" class="form-control cboSelectFiltro">
                            <option value="0">Todas</option>
                            @foreach (var UG in ((List<UnidadeGestora>)ViewBag.UnidadesGestoras).OrderBy(ug => ug.unidadeGestoraIDSIAFEM))
                            {
                                <option value="@UG.unidadeGestoraIDSIAFEM" @(Request["ug"] != null && Request["ug"] == UG.unidadeGestoraIDSIAFEM ? "selected" : "")>@UG.unidadeGestoraIDSIAFEM - @UG.nomeUG</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="tipoMaterial">Tipo de material</label><br />
                        <select id="tipoMaterial" class="form-control cboSelectFiltro">
                            <option value="0" selected>Selecione</option>
                            <option value="33903000">Consumo</option>
                            <option value="44905200">Permanente</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="txtDataInicial">Período</label><br />
                        <div class="input-daterange input-group" id="periodo">
                            <input id="dataInicial" name="dataInicial" type="text" class="form-control" value="" />
                            <span class="input-group-addon">a</span>
                            <input type="text" class="form-control" name="end" id="dataFinal" value="" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-md-12">
                    <button type="button" class="btn btn-primary" onclick="exibirComprasMateriais();">Consultar</button>
                </div>
            </div>
        </div>
    </div>
</form>
@if (!String.IsNullOrWhiteSpace(ViewBag.DataAtualizacao))
{
    <div class="container chartFooter">* Última atualização de compras: <b>@DateTime.Parse(ViewBag.DataAtualizacao.ToString()).ToString("dd/MM/yyyy")</b> / Fonte dos dados: SIAFEM / SUPER</div>
}
<div class="row">
    <div class="container-fluid" id="tabelaDadosContainer">
    </div>
</div>

@section AposFooter{
    <script>
        $(document).ready(function () {
            $('.input-daterange').datepicker({
                language: "pt-BR",
                format: "dd-mm-yyyy"
            });
            exibirComprasMateriais();
        });

            function parseDate(date) {
                    return new Date(Number(date.match(/(\d)+/)[0])).toLocaleString().split(" ")[0];
            }

        function exibirComprasMateriais() {

            let dataInicial = $('#dataInicial').datepicker('getDate'), dataFinal = $('#dataFinal').datepicker('getDate');

            $('#tabelaDadosContainer').html('<i class="fa fa-cog fa-spin"></i> Carregando dados...');
            $('#dataInicial').datepicker('hide');
            $('#dataFinal').datepicker('hide');
            $.post('@Url.Action("ComprasMateriais")', {
                codUnidadeGestora: $('#cboUnidadeGestora').val(),
                tipoMaterial: $('#tipoMaterial').val(),
                dataInicial: dataInicial == null ? dataInicial : dataInicial.toYMD(),
                dataFinal: dataFinal == null ? dataFinal : dataFinal.toYMD()
            })
                .done(function (data) {
                    if (data.msgErro != null) {
                        $('#tabelaDadosContainer').html('<div class="alert alert-warning" role="alert"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><span class="sr-only">Erro:</span>' + data.msgErro + '</div>');
                    }
                    else {

                        data.dados = data.dados.map((item) => {
                            item.DataDocumento = parseDate(item.DataDocumento);
                            //item.valorDespesa = "R$ " + parseFloat(item.ValorEmpenhada).toFixed(2).replace(".", ",");
                            return item;
                        });


                        $('#tabelaDadosContainer').html(Mustache.render($('#templateDados').html(), data));
                        $('#tabelaDadosContainer > #tabelaDados').dataTablePadrao({ "colunasFixas": 1 });
                        if (data.msgInfo != null) {
                            $('#tabelaDadosContainer').prepend('<div class="alert alert-info" role="alert"><span class="sr-only">Informação:</span><strong>Informação </strong>' + data.msgInfo + '</div>');
                        }
                    }
                })
                .fail(function () {
                    $('#tabelaDadosContainer').html('<div class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><span class="sr-only">Erro:</span><strong>Erro: </strong>Ocorreu um erro ao efetuar a pesquisa. Caso o problema persista, entre em contato com a CGE através do e-mail <a href="mailto:contato@cge.ro.gov.br">contato@cge.ro.gov.br</a>.</div>');
                });
        }
    </script>
    <script id="templateDados" type="text/html">
        <table class="table table-striped" id="tabelaDados">
            <thead>
                <tr>
                    <th>Detalhar</th>
                    <th>Exercício</th>
                    <th>Cod. UG</th>
                    <th>Num. Empenho</th>
                    <th>Data do documento</th>
                    <th>Credor</th>
                    <th>Especificação Despesa</th>
                    <th>Valor Despesa</th>
                    <th hidden>Documento</th>
                </tr>
            </thead>
            <tbody>
                {{#dados}}
                <tr>
                    <td><a href="@(Url.Action("DetalhesCompra", "Grafico"))?exercicio={{ Exercicio }}&ug={{UG}}&numEmpenho={{NumEmpenho}}&especificacaoDespesa={{EspecificacaoDespesa}}&valorDespesa={{valorDespesa}}&documento={{Documento}}"><i class="glyphicon glyphicon-search"></i></a></td>
                    <td><b>{{Exercicio}}</b></td>
                    <td>{{UG}}</td>
                    <td>{{NumEmpenho}}</td>
                    <td>{{DataDocumento}}</td>
                    <td>{{Credor}}</td>
                    <td>{{EspecificacaoDespesa}}</td>
                    <td>{{valorDespesa}}</td>
                    <td hidden>{{Documento}}</td>
                </tr>
                {{/dados}}
            </tbody>
            <tfoot>
                <tr>
                    <th>Detalhar</th>
                    <th>Exercício</th>
                    <th>Cod. UG</th>
                    <th>Num. Empenho</th>
                    <th>Data do documento</th>
                    <th>Credor</th>
                    <th>Especificação Despesa</th>
                    <th>Valor Despesa</th>
                    <th hidden>Documento</th>
                </tr>
            </tfoot>
        </table>
    </script>

    <link href="~/Content/bootstrap-chosen.css" rel="stylesheet" />
    <script src="~/scripts/chosen.jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $(document).ready(function () {
                $(".cboSelectFiltro").chosen();
            });
        });
    </script>
}

TransparenciaRO.Web/Views/Grafico/Grafico.cshtml
@using TransparenciaRO.Web.Controllers
@model List<GraficoController.HighchartsSeriesEntry>
@section Head{
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
}
@{
    if (ViewBag.Title == "")
    {
        ViewBag.Title = "Gráfico";
    }
}
<div class="chartContainer">
    <h2>Receita Total</h2>
    <div id="grafico" class="grafico"></div>
</div>

@section AposFooter
{
    <script>
        var chartData = @Html.Raw(Json.Encode(Model));
        var categorias = @(ViewBag.Categories != null ? Html.Raw(Json.Encode(ViewBag.Categories))  : "null");
        var dadosDrilldown =  @(ViewBag.DrilldownSeries != null ? Html.Raw(Json.Encode(ViewBag.DrilldownSeries)) : "null");

        var sliderAno = null;
        var chart;

        function atualizaGrafico()
        {
            chart.xAxis[0].setCategories(nomesValores, true, true);
            chart.series[0].setData(valores, true, true);
            chart.series[1].setData(valoresPrevista, true, true);
        }

        $(document).ready(function () {
            preparaGrafico('@ViewBag.Title', 'grafico', chartData, categorias, dadosDrilldown);
        });
    </script>
}